name: Daily Stock Analysis

on:
  schedule:
    # 每个工作日早上8:30 (北京时间，UTC+8，所以这里是00:30 UTC)
    - cron: '30 0 * * 1-5'
  workflow_dispatch:  # 允许手动触发

jobs:
  daily-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create data directory
      run: |
        mkdir -p data
    
    - name: Run daily analysis
      env:
        TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
        WECHAT_APP_ID: ${{ secrets.WECHAT_APP_ID }}
        WECHAT_APP_SECRET: ${{ secrets.WECHAT_APP_SECRET }}
        WECHAT_STOCK_TEMPLATE_ID: ${{ secrets.WECHAT_STOCK_TEMPLATE_ID }}
      run: |
        echo "开始每日股票分析..."
        python scripts/final_working_analysis.py
    
    - name: Send WeChat notification
      if: success()
      env:
        WECHAT_APP_ID: ${{ secrets.WECHAT_APP_ID }}
        WECHAT_APP_SECRET: ${{ secrets.WECHAT_APP_SECRET }}
        WECHAT_STOCK_TEMPLATE_ID: ${{ secrets.WECHAT_STOCK_TEMPLATE_ID }}
      run: |
        echo "发送微信通知..."
        python scripts/send_wechat_notification.py send-daily
    
    - name: Upload analysis report
      uses: actions/upload-artifact@v3
      with:
        name: daily-analysis-report-${{ github.run_number }}
        path: daily_analysis_report.json
        retention-days: 30
    
    - name: Notify on failure
      if: failure()
      run: |
        echo "分析失败，请检查日志"
