name: Daily Stock Analysis

on:
  schedule:
    # 每个工作日早上8:30 (北京时间，UTC+8，所以这里是00:30 UTC)
    - cron: '30 0 * * 1-5'
  workflow_dispatch:  # 允许手动触发

jobs:
  daily-analysis:
    runs-on: ubuntu-latest

    env:
      TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
      FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
      DATABASE_URL: sqlite:///stock_analysis.db
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      WECHAT_APP_ID: ${{ secrets.WECHAT_APP_ID }}
      WECHAT_APP_SECRET: ${{ secrets.WECHAT_APP_SECRET }}
      WECHAT_STOCK_TEMPLATE_ID: ${{ secrets.WECHAT_STOCK_TEMPLATE_ID }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create data directory
      run: |
        mkdir -p data
        mkdir -p logs
        mkdir -p reports

    - name: Test basic functionality
      run: |
        echo "测试基础功能..."
        python -c "
        import os
        os.environ['TUSHARE_TOKEN'] = '${{ secrets.TUSHARE_TOKEN }}'
        os.environ['FLASK_SECRET_KEY'] = '${{ secrets.FLASK_SECRET_KEY }}'
        from app import create_app, db
        app = create_app()
        with app.app_context():
            db.create_all()
            print('✅ 数据库初始化成功')
        "

    - name: Run daily analysis
      env:
        TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
        WECHAT_APP_ID: ${{ secrets.WECHAT_APP_ID }}
        WECHAT_APP_SECRET: ${{ secrets.WECHAT_APP_SECRET }}
        WECHAT_STOCK_TEMPLATE_ID: ${{ secrets.WECHAT_STOCK_TEMPLATE_ID }}
      run: |
        echo "开始每日股票分析..."
        python scripts/daily_analysis.py

    - name: Send WeChat notification
      if: success()
      env:
        WECHAT_APP_ID: ${{ secrets.WECHAT_APP_ID }}
        WECHAT_APP_SECRET: ${{ secrets.WECHAT_APP_SECRET }}
        WECHAT_STOCK_TEMPLATE_ID: ${{ secrets.WECHAT_STOCK_TEMPLATE_ID }}
      run: |
        echo "发送微信通知..."
        python scripts/send_wechat_notification.py send-daily
    
    - name: Upload analysis report
      uses: actions/upload-artifact@v4
      with:
        name: daily-analysis-report-${{ github.run_number }}
        path: |
          reports/
          logs/
        retention-days: 30
    
    - name: Notify on failure
      if: failure()
      run: |
        echo "分析失败，请检查日志"
